# Generated by Django 4.1.5 on 2023-01-20 10:27

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Категория оборудования",
                "verbose_name_plural": "Категории оборудования",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название должности"),
                ),
            ],
            options={
                "verbose_name": " Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Марка")),
                (
                    "model",
                    models.CharField(max_length=100, null=True, verbose_name="Модель"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "information_employee",
                    models.FileField(
                        upload_to="description_equipment/%Y/%m/%d/",
                        verbose_name="Характеристики",
                    ),
                ),
                (
                    "additional_information",
                    models.URLField(
                        null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото"),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Расположение"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.equipmentcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=50, null=True, verbose_name="Отчество"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="RU",
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "position_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="EquipmentEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.employee",
                        verbose_name="Сотрудник, допущенный к работе",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование - Сотрудник",
                "verbose_name_plural": "Оборудование - Сотрудник",
                "unique_together": {("equipment", "employee")},
            },
        ),
    ]
