# Generated by Django 4.1.5 on 2023-01-18 18:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNCLathe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Марка")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "move_x",
                    models.IntegerField(verbose_name="Перемещение по оси X, мм"),
                ),
                (
                    "move_y",
                    models.IntegerField(verbose_name="Перемещение по оси Z, мм"),
                ),
                (
                    "spindle_speed",
                    models.IntegerField(verbose_name="Обороты шпинделя, об/мин"),
                ),
                (
                    "number_of_positions",
                    models.IntegerField(
                        verbose_name="Количество позиций в револьверной головке"
                    ),
                ),
                ("length", models.IntegerField(verbose_name="Длинна")),
                ("width", models.IntegerField(verbose_name="Ширина")),
                ("height", models.IntegerField(verbose_name="Высота")),
                ("weight", models.IntegerField(verbose_name="Вес")),
                (
                    "additional_information",
                    models.URLField(
                        null=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото"),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Расположение"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название должности"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=50, null=True, verbose_name="Отчество"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        region="RU",
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "position_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CNCLatheEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnc_lathe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.cnclathe",
                        verbose_name="Токарный станок с ЧПУ",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.employee",
                        verbose_name="Сотрудник, допущенный к работе",
                    ),
                ),
            ],
        ),
    ]
