# Generated by Django 4.1.5 on 2023-01-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cnclathe",
            options={
                "verbose_name": "Токарный станок с ЧПУ",
                "verbose_name_plural": "Токарные станки с ЧПУ",
            },
        ),
        migrations.AlterModelOptions(
            name="cnclatheemployee",
            options={"verbose_name": "Токарный станок с ЧПУ - Сотрудник"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AlterModelOptions(
            name="equipmentcategory",
            options={
                "verbose_name": "Категория оборудования",
                "verbose_name_plural": "Категории оборудования",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": " Должность", "verbose_name_plural": "Должности"},
        ),
    ]
