# Generated by Django 4.1.5 on 2023-01-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производства',
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(max_length=100, verbose_name='Цех')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_catalog.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Расположение',
                'verbose_name_plural': 'Расположение',
                'unique_together': {('production', 'workshop')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_catalog.equipment', verbose_name='Оборудование')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_catalog.location', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Оборудование - Расположение',
                'verbose_name_plural': 'Оборудование - Расположение',
                'unique_together': {('location', 'equipment')},
            },
        ),
    ]
