# Generated by Django 4.1.5 on 2023-01-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_catalog", "0002_alter_cnclathe_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cnclatheemployee",
            old_name="cnc_lathe_id",
            new_name="cnc_lathe",
        ),
    ]
