# Generated by Django 4.1.5 on 2023-01-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_catalog', '0002_production_remove_equipment_location_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер цеха')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_catalog.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Расположение',
                'verbose_name_plural': 'Расположение',
            },
        ),
        migrations.AlterField(
            model_name='equipmentlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment_catalog.workshops', verbose_name='Расположение'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
