# Generated by Django 4.1.5 on 2023-01-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_catalog", "0003_rename_cnc_lathe_id_cnclatheemployee_cnc_lathe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cnclatheemployee",
            options={
                "verbose_name": "Токарный станок с ЧПУ - Сотрудник",
                "verbose_name_plural": "Токарный станок с ЧПУ - Сотрудник",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cnclatheemployee",
            unique_together={("cnc_lathe", "employee")},
        ),
    ]
