# Generated by Django 4.1.5 on 2023-01-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_catalog", "0004_alter_cnclatheemployee_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Марка")),
                (
                    "model",
                    models.CharField(max_length=100, null=True, verbose_name="Модель"),
                ),
                (
                    "information_employee",
                    models.FileField(
                        upload_to="description_equipment/%Y/%m/%d/",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="photos/%Y/%m/%d", verbose_name="Фото"),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Расположение"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.equipmentcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="EquipmentEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.employee",
                        verbose_name="Сотрудник, допущенный к работе",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment_catalog.equipment",
                        verbose_name="Оборудование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование - Сотрудник",
                "verbose_name_plural": "Оборудование - Сотрудник",
                "unique_together": {("equipment", "employee")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="cnclatheemployee",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cnclatheemployee",
            name="cnc_lathe",
        ),
        migrations.RemoveField(
            model_name="cnclatheemployee",
            name="employee",
        ),
        migrations.DeleteModel(
            name="CNCLathe",
        ),
        migrations.DeleteModel(
            name="CNCLatheEmployee",
        ),
    ]
