# Generated by Django 4.1.5 on 2023-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_catalog", "0005_equipment_equipmentemployee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="additional_information",
            field=models.URLField(null=True, verbose_name="Дополнительная информация"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="information_employee",
            field=models.FileField(
                upload_to="description_equipment/%Y/%m/%d/",
                verbose_name="Характеристики",
            ),
        ),
    ]
